### ISSUE TITLE
make_unique

### ISSUE THREAD

**Issue by hatsusato** [kmc-jp/Klang#23]
- `make_unique`を導入したいのですが、どのファイルに書けばいいでしょうか。
  1. 現状ではAST周りで使うので、`ast.hpp`に入れる。
  2. `utility.hpp`を作ってそこにもろもろのユーティリティを入れる。
  3. `make_unique.hpp`を作る。
  4. `memory.hpp`を作ってその中に`#include <memory>`と`make_unique`の実装を入れて、`<memory>`の代わりに使う。
  5. その他。

**Comment by hatsusato** [comment]
あと`make_unique`を`klang namespace`に入れるか否か。

**Comment by nna774** [comment]
c++14 フラグを付ける って選択肢も一応

**Comment by nna774** [comment]
流石にはげしいか

**Comment by nna774** [comment]
ii. かiii. かなぁ 
iv. は気持ち悪いきもする。

**Comment by hatsusato** [comment]
どうせC++14に入る機能だから、iv.でいいんじゃないかと思った。
C++14時代の`<memory>`をエミュレートする感じ。
あと`klang::make_unique`でいいんじゃないかと思った。

**Comment by nna774** [comment]
#26 でiv. の方針で行くことになりました。
