### ISSUE TITLE
Eitherがほしい

### ISSUE THREAD

**Issue by hatsusato** [kmc-jp/Klang#58]
- `Parser`の実装を見直す(エラー処理をする)にあたって、`Either`クラスがほしい気がしたので実装したいです。
- いい感じの実装を他で見つけた人は教えてください。
- 方針
  - `union`で作る
    - 自然で妥当な実装。でも面倒。

``` C++
template <typename Left, typename Right>
class Either {
  bool is_right_;
  union {
    Left left_;
    Right right_;
  };
};
```
- `optional`で作る
  - 比較的楽な実装。面倒事はoptionalがやってくれる。

``` C++
template <typename Left, typename Right>
class Either {
  optional<Left> left_;
  optional<Right> right_;
};
```
- インターフェースについての議論
  - コンストラクタ
    - 第一引数は`LeftTag`型または`RightTag`型。
    - 省略した場合は`Right`型で構築できるようにする？
  - アクセサ
    - `is_right()`を返す`operator bool()`を提供する？
    - `right_value()`を返す`operator*()`、`operator->()`を提供する？

**Comment by nna774** [comment]
とりあえず`optional` 使って実装すればいいんじゃないかと思います。
インターフェースさえしっかりしていたら、後からいいかんじに差し替えることも可能でしょうし。

```
- 第一引数は`LeftTag`型または`RightTag`型。
- 省略した場合は`Right`型で構築できるようにする？
```

良さそう。

```
- `is_right()`を返す`operator bool()`を提供する？
```

あったほうが良さそう？

```
- `right_value()`を返す`operator*()`、`operator->()`を提供する？
```

これはあっても良いと思う。
`Left` だった時にどうするかはいくつかありそう
- なにも考えずに`Right` を返す。(危いけど効率は良さそう？)
- チェックして例外投げる。(投げたところで復帰できるのか)
- チェックしてassert する。

このへん？

**Comment by hatsusato** [comment]
使い方のイメージ
- before

``` C++
ast::AdditiveExpressionPtr Parser::parse_additive_expression() {
  if (auto lhs_expression = parse_multiplicative_expression()) {
    const auto s = snapshot();
    if (parse_symbol("+")) {
      if (auto rhs_expression = parse_additive_expression()) {
        return make_unique<ast::AddExpressionData>(
            std::move(lhs_expression), std::move(rhs_expression));
      }
      rewind(s);
    } else if (parse_symbol("-")) {
      if (auto rhs_expression = parse_additive_expression()) {
        return make_unique<ast::SubtractExpressionData>(
            std::move(lhs_expression), std::move(rhs_expression));
      }
      rewind(s);
    }
    return std::move(lhs_expression);
  }
  return nullptr;
}
```
- after

``` C++
class ErrorType;
template <class T>
using WithError = Either<ErrorType, T>;
WithError<ast::AdditiveExpressionPtr> Parser::parse_additive_expression() {
  using Right = ast::AdditiveExpressionPtr;
  auto lhs_expression = parse_multiplicative_expression();
  if (!lhs_expression) {
    return make_error<Right>(lhs_expression);  // エラーを転送
  }
  const auto s = snapshot();
  const auto symbol = parse_symbol();
  if (symbol.is("+")) {
    auto rhs_expression = parse_additive_expression();
    if (!rhs_expression) {
      return make_error<Right>(rhs_expression);
    }
    return make_unique<ast::AddExpressionData>(
        std::move(*lhs_expression), std::move(*rhs_expression));
  } else if (symbol.is("-")) {
    auto rhs_expression = parse_additive_expression();
    if (!rhs_expression) {
      return make_error<Right>(rhs_expression);
    }
    return make_unique<ast::SubtractExpressionData>(
        std::move(*lhs_expression), std::move(*rhs_expression));
  }
  rewind(s);
  return std::move(*lhs_expression);
}
```

**Comment by angelworm** [comment]
parse_symbolが無引数になるのは何の意図ですか?

**Comment by nna774** [comment]
関数呼び出しというより、コンストラクタ呼び出し って意図なのでは(名前変えるべきって気もするけど)

**Comment by angelworm** [comment]
pureじゃないコンストラクタつらいなぁ

**Comment by angelworm** [comment]
Rightをmake_errorで作るんだったら、Eitherよりも意味のある型名を型名を与えるべきだと思う。

**Comment by nna774** [comment]
`WithError` なのでは……
別名でしかないけど

**Comment by angelworm** [comment]
`WithError`とは

**Comment by nna774** [comment]
1~3 行目でusing されて別名与えられています。

**Comment by angelworm** [comment]
つまり、あくまで`make_error`は`WithError<T>`を返す関数だから問題ないという話か。
なら問題ないのかな。

**Comment by angelworm** [comment]
ではもう一つ。

```
auto rhs_expression = parse_additive_expression();
```

では`rhs_expression`も`WithError`で返ってくるのに

```
return make_error<Right>(rhs_expression);
```

ではもう一回ラップしているのは意味があるのでしょうか。

**Comment by nna774** [comment]
それは思いました。

そのままreturn すればいい気がする。

**Comment by hatsusato** [comment]
> parse_symbolが無引数になるのは何の意図ですか?

`parse_symbol()`だけほかの`parse_*()`系の関数とシグネチャが異なるので、合わせるべきだと考えました。
上では`parse_symbol()`はシンボル情報を保持するクラスを返すような想定になっていますが、`string`を返すだけでいい気がしてきました。

**Comment by nna774** [comment]
`if (!rhs_expression) {
  return make_error<Right>(rhs_expression);
}`
が頻出するの、なんか辛いけど、マクロにするのはちょっとアレかなぁ…… したほうがコード的にはきれいになる？

**Comment by hatsusato** [comment]
そのぐらいのマクロは許容範囲だと思います。
名前が思いつかないけど。

**Comment by hatsusato** [comment]
> ではもう一回ラップしているのは意味があるのでしょうか。

`WithError<T>`型から`WithError<U>`型への暗黙変換が許されないからです。
例えば、`parse_primary_expression()`の中で`parse_identifier()`が`WithError<ast::IdentifierPtr>`型のleft値を返したとします。
`ast::IdentifierPtr`と`ast::PrimaryExpressionPtr`の間には関係がないので、`WithError<ast::IdentifierPtr>`を戻り値の型`WithError<ast::PrimaryExpressionPtr>`に変換できません。
なので、明示的に変換するために、`make_error()`転送関数を導入したというわけです。
`make_error()`は引数の`WithError`をleft値であると思って変換します。

**Comment by angelworm** [comment]
`parse_symbol()`の来る箇所にIdentiferが来た場合、返り値はどのようになるのでしょうか。
正直インターフェースが合わないのなら、追加のラッパーをつけてでも前の形の方が良いのでは無いでしょうか。
予期しないトークン読み出しが無くなる分、`snapshot()`をとる必要が無くなります。

**Comment by hatsusato** [comment]
`WithError<std::string>`のleft値です。
上は言葉足らずでしたね。

> `string`を返すだけ

は`WithError<string>`のことですね。

**Comment by angelworm** [comment]
`WithError<T>`が`is()`メンバを持つのですか?

**Comment by hatsusato** [comment]
持たないです。
`parse_symbol()`が`WithError`を返すことにすると、afterのコードは動かないです。

``` C++
if (symbol) {
  if (*symbol == "+") {
  }
}
```

みたいになると思います。

**Comment by angelworm** [comment]
それ、関数定義パーサーでもやるの?

**Comment by nna774** [comment]
Either、ちゃんとモナディックに、失敗値ならそのまま伝播して、成功値のときだけ処理するようにうまくできないかな……。

**Comment by hatsusato** [comment]
シンボルは他の要素とは異なり、具体的なシンボルの文字列に依存するので、`parse_symbol(string)`がいい気がしてきました。

**Comment by hatsusato** [comment]
http://d.hatena.ne.jp/gintenlabo/20100528/1275052141
ここ読んで思ったんですが、自作は絶対面倒くさいですね。
`union`で作るの諦めて、多少のメモリ効率の犠牲を覚悟でこのまま`optional`で行くのが良さそう。
真面目にSFINAEして対処するのやりたくないので。

**Comment by nna774** [comment]
しばらくはunion 使わなくていいに賛成〜
だれかまともなunion 番を作ってPR くるまではいいでしょう。

**Comment by nna774** [comment]
Optional版: fe979a597e6cf78cbfcbfc89c6d57fe004823298
Union版: 5bc8136026772e8575d4ab52dd14db8d50b79df4
にて解決
